name: Generate SBOM and Upload to Dependency-Track

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  generate-and-upload-sbom:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm install

    - name: Install CycloneDX CLI
      run: npm install -g @cyclonedx/cyclonedx-npm

    - name: Generate SBOM
      run: |
        cyclonedx-npm  -o sbom.json

    - name: Upload SBOM to Dependency-Track
      env:
        API_KEY: ${{ secrets.DEPENDENCY_TRACK_API_KEY }}
        SERVER_URL: ${{ secrets.DEPENDENCY_TRACK_SERVER_URL }}
        PROJECT_NAME: ${{ secrets.DEPENDENCY_TRACK_PROJECT_NAME }}
        PROJECT_VERSION: ${{ github.ref_name }}
      run: |
        echo "DEBUG: SERVER_URL = ${SERVER_URL}"
        echo "DEBUG: Full URL = ${SERVER_URL}/api/v1/bom"
        echo "DEBUG: PROJECT_NAME = ${PROJECT_NAME}"
        echo "DEBUG: PROJECT_VERSION = ${PROJECT_VERSION}"
        
        # Check if SBOM file exists
        if [ ! -f "sbom.json" ]; then
          echo "ERROR: sbom.json file not found"
          exit 1
        fi
        
        # Upload SBOM to Dependency-Track
        curl -v -X POST \
          "http://http://74.162.33.10:8081/api/v1/bom" \
          -H "X-Api-Key: ${API_KEY}" \
          -H "Content-Type: multipart/form-data" \
          -F "projectName=${PROJECT_NAME}" \
          -F "projectVersion=latest" \
          -F "bom=@sbom.json"

    - name: Upload SBOM artifact
      uses: actions/upload-artifact@v4
      with:
        name: sbom
        path: sbom.json
